[package]
name = "caso3"
version = "0.1.0"
authors = ["Javyre90 <56284957+Javyre90@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
